### ISSUE TITLE
大神有木有详细教程呢

### ISSUE THREAD

**Issue by yangxiaoge** [wuchangfeng/MarkDownHelper#1]
拖动之后闪退了

**Comment by wuchangfeng** [comment]
你好，才看见不好意思。
1. 先保证各个配置的参数都没有问题。
2. 可以先调试一下脚本,用 cmd 窗口进入脚本所在的目录,运行 Python MdScripts.py 如果什么都没有就表示没有问题。
3. 如果是 windwos 平台的话，可能要添加一个注册表。
4. 另外 cmd 窗口安装一下 七牛的 sdk： pip install Qiniu

如果还有问题,请告知。

**Comment by wuchangfeng** [comment]
拖动闪退也是正常的,可有右键黏贴一下,看看有没有 url 生成。

**Comment by yangxiaoge** [comment]
Traceback (most recent call last):
  File "MdScript.py", line 16, in <module>
    if os.path.exists(result_file):
NameError: name 'result_file' is not defined

**Comment by wuchangfeng** [comment]
@yangxiaoge 你好,现在应该可以了。您在克隆一下。问题是由于我当时做 v3 的时候,没有将多余代码移除。如果能够运行的话，请告知。谢谢。

**Comment by yangxiaoge** [comment]
连接生成了,打开报错.token not specified!
![22](https://cloud.githubusercontent.com/assets/12471093/15638473/96983e36-2653-11e6-8727-55beb68363d7.png)

**Comment by wuchangfeng** [comment]
@yangxiaoge 能否贴出链接或者 你也可以在 github 上的 readMe 中黏贴该链接看看是否能够显示出对应的图像。

**Comment by yangxiaoge** [comment]
http://naxiexiaojiyi1.qiniudn.com/1.png

markdown中也是不显示图片的

**Comment by wuchangfeng** [comment]
奇怪啊,我又测试了一下，可以啊。加我qq吧:437806668

**Comment by wuchangfeng** [comment]
@yangxiaoge 你的七牛空间是私有的吗？我查了一下你的提示错误，说是空间是私有的。
