### ISSUE TITLE
希望支持文件夹

### ISSUE THREAD

**Issue by DoubleShift** [wuchangfeng/MarkDownHelper#2]
希望支持文件夹的上传

**Comment by wuchangfeng** [comment]
@DoubleShift 是想把文件夹里面的内容上传到云存储还是？

**Comment by DoubleShift** [comment]
@wuchangfeng 我博客是用的 /2015/06/img01.jpg ; /2015/07/img02.jpg 这样的格式的，而这个脚本没有支持这个前缀/文件夹。希望支持这种形式的上传。

**Comment by wuchangfeng** [comment]
好，等我考完试，我试试看 行不行。

**Comment by wuchangfeng** [comment]
你所说的是这个意思吗：这个脚本生成的 URl 是这种形式: 感叹号+[ ] + ()。而你的博客需要的 URl 是： /2015/06/img01.jpg 这种形式？

因为在 MarkDown 语法中图片的引用形式是：![]()。

不知道我有没有理解你的意思。

**Comment by DoubleShift** [comment]
![1](https://cloud.githubusercontent.com/assets/5484152/16543675/47d10e52-40ea-11e6-85e6-cfd7df4dcf98.png)
脚本上传的是15092603.jpg这种的。然后坏处就是不能有重复的文件名，所以我就按日期放不同目录，qiniu sync的一个python脚本上传后就是按照目录 2012/10/xx.jpg 上传的。不知道说明白没有
and 十分感谢。

**Comment by wuchangfeng** [comment]
加我 qq 细说啊：437806668

**Comment by wuchangfeng** [comment]
@DoubleShift 你好。我想问题已经修复了。最新的版本中:我获取系统当前的年月日以及具体的时间单位来给每一张图片命名。像类似于 #**<<??{}.png 这样杂乱无章格式的 img 最后上传之后都会统一命名为 2016/7/12/09:42:50.png 这种格式的图片。当然也不可能存在重复命名的情况。
