### ISSUE TITLE
很奇怪的问题

### ISSUE THREAD

**Issue by lfengzhang** [wuchangfeng/MarkDownHelper#3]
![09](https://cloud.githubusercontent.com/assets/12016007/16544059/14797802-4129-11e6-8266-89ac39689d73.jpg)
只有这张图片上传上去没反映，其他图片没问题...

**Comment by lfengzhang** [comment]
又测试了一波，好像是图片尺寸太大的问题？小一点的就没事

**Comment by lfengzhang** [comment]
另外一个建议是，删除文件的时候最好不要直接删除？丢入回收站是不是更为妥当？

**Comment by wuchangfeng** [comment]
@amlingfeng 你好。才看见你的 issue。
-  图片我晚上 down 下来，自己上传试试看。你可以试一下带有压缩功能的脚本。看看是不是分辨率的问题。
-  恩，这个功能主要跟 Python 提供的函数有关。好像是 os.remove() 。系统级别的删除，当时想着即使回收站内也没有了。还可以在云平台下载下来。所以这个功能就这么马虎的搞出来了。回头我查查，有没有别的选择。

欢迎一起完善。

**Comment by lfengzhang** [comment]
@wuchangfeng 
嗯，你的这个项目是现阶段我唯一看得懂一点的python项目了，准备好好研究下大大的代码，学习下python~

**Comment by wuchangfeng** [comment]
@amlingfeng 图片可以上传。我把你的图片下载下来的。之前也不能上传，主要原因是这张图的命名不规范：-222--cfff--.jpg 像这种带特殊字符或者中文的就不能处理。我改成 img1.jpg 就能上传。这也是 issue1 提的一个问题。后面一块改吧。

**Comment by lfengzhang** [comment]
@wuchangfeng 我是纯数字啊…这个bug神奇

**Comment by wuchangfeng** [comment]
@amlingfeng 你试着改一下命名看看。img1.jpg。哎，估计还是当初没设计好。因为用正则的。

**Comment by lfengzhang** [comment]
@wuchangfeng 正则大大（两眼放光）！

**Comment by wuchangfeng** [comment]
@amlingfeng 说错了,应该用正则，来判断图片的命名。当初没用，现在我也没时间看看当时怎么写的了。
哪里不懂，你可以加我的 qq 问。qq 在项目主页可以看得到。

**Comment by wuchangfeng** [comment]
@amlingfeng 今天查了一下删除到回收站的功能好像有 http://www.programgo.com/article/8763801235/ 但是,这不是我最开始的想法。你需要的话可以参考那个连接。这个 issue 就关闭了。有什么问题再联系。
